IS403Project1/IS403Project1/Models/MissionAndQuestions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IS403Project1.Models
{
    public class MissionAndQuestions
    {
        [Key]
    
        public int user_ID { get; set; }
        public int mission_ID { get; set; }
        public string question { get; set; }
        public string answer { get; set; }

        public string missionName { get; set; }
        public string missionPresidentName { get; set; }
        public string missionAddress { get; set; }
        public string missionLanguage { get; set; }
        public string missionClimate { get; set; }
        public string missionDominantReligion { get; set; }
        public string missionFlag { get; set; }
    }
}

IS403Project1/IS403Project1/Models/MissionQuestions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IS403Project1.Models
{
    [Table("MissionQuestions")]
    public class MissionQuestions
    {
        [Key]
        public int MissionQuestion_ID { get; set; }
        public int user_ID { get; set; }
        public int mission_ID { get; set; }
        public string question { get; set; }
        public string answer { get; set; }

    }
}

IS403Project1/IS403Project1/Models/Missions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IS403Project1.Models
{
    [Table("Missions")]
 
    public class Missions
    {
        [Key]
        public int mission_ID { get; set; }
        public string missionName { get; set; }
        public string missionPresidentName { get; set; }
        public string missionAddress { get; set; }
        public string missionLanguage { get; set; }
        public string missionClimate { get; set; }
        public string missionDominantReligion { get; set; }
        public string missionFlag { get; set; }

    }
}

IS403Project1/IS403Project1/Models/users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IS403Project1.Models
{
    [Table("Users")]
    public class users
    {
       [Key]
        public int user_ID { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }

    }
}

IS403Project1/IS403Project1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IS403Project1.Controllers
{
    //This is my comment
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            List<SelectListItem> subjects = new List<SelectListItem>();
            subjects.Add(new SelectListItem { Text = "one", Value = "0" });
            subjects.Add(new SelectListItem { Text = "two", Value = "1" });
            subjects.Add(new SelectListItem { Text = "three", Value = "2" });
            ViewBag.subjects = subjects;

            ViewBag.Message = "Your contact page.";

            ViewBag.Subject = "Subject";

            return View();

        }

        public ActionResult updateSubject()
        {
            ViewBag.Subject = "One";

            return View();
        }
    }
}

IS403Project1/IS403Project1/Controllers/MissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IS403Project1.Models;
using IS403Project1.DAL; 

namespace IS403Project1.Controllers
{
    public class MissionController : Controller
    {
        private MissionContext db = new MissionContext();
        // GET: Mission
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MissionPage(int mission_ID)
        {
            
            
            IEnumerable<MissionQuestions> questions = db.Database.SqlQuery<MissionQuestions>(
                "SELECT MissionQuestions.MissionQuestion_ID, MissionQuestions.question, MissionQuestions.answer, " +
                "MissionQuestions.user_ID, MissionQuestions.mission_ID " +
                "FROM MissionQuestions "+
                "WHERE MissionQuestions.mission_ID = " + mission_ID);
                

            IEnumerable<Missions> missions = db.Database.SqlQuery<Missions>(
                "SELECT Missions.mission_ID, Missions.missionName, Missions.missionPresidentName, Missions.missionAddress, Missions.missionLanguage, " +
                "Missions.missionClimate, Missions.missionDominantReligion, Missions.missionFlag " +
                "FROM Missions " +
                "WHERE Missions.mission_ID = " + mission_ID);

            ViewBag.questions = questions;
            ViewBag.missions = missions;   

            return View(missions);
        }
    }
}

IS403Project1/IS403Project1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="jumbotron">
    <br />
    <br />
    <div style="opacity: 0.7; background-color: white; border-radius: 20px; padding: 5px;">
        <h2>Prepare to Serve</h2>
        <h3>Our Mission</h3>
        <p>
            Ready to serve a mission but don't know where to start? At Prepare to Serve,
            we aim to get the right information to you so you can feel confident when you apply.
            We provide fake information from fake missionaries that have recently returned from their
            missions.
        </p>
    </div>
</div>

IS403Project1/IS403Project1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Group 8 Rocks Road<br />
    Provo, Ut 84604<br />
    <abbr title="Phone">P:</abbr>
    4801.422.8888
</address>

<address>
    <strong>Support:</strong>   <a href="Tannermorse.net">Tannermorse.net</a><br />
</address>

<div class="container">
    <form>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
        </div>
        <div class="form-group">
            @Html.DropDownList("subjects")
        </div>
        <div class="form-group">
            <label>Body:</label>
            <textarea class="form-control" id="body" placeholder="Body" name="body" style="height: 150px;"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>

IS403Project1/IS403Project1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" id="center">
    <h1>Welcome!</h1>
    <p class="lead" id="jumbotext">So you wanna go on a mission?!</p>
    <p><a href="@Url.Action("Index", "Mission")" class="btn btn-success btn-lg">Learn More Here! &raquo;</a></p>
</div>

<h2><em>Our goal is to help you learn the ins and outs of any mission where you may serve.</em></h2>

<hr />

<div class="row">
    <div class="col-md-4">
        <h2>Learn</h2>

        <p>
            <em>“For he that diligently seeketh shall find; and the mysteries of God shall be unfolded unto them, by the power of the Holy Ghost, as well in these times as in times of old”</em>
        </p>
        <p>- 1 Nephi 10:19</p>
    </div>
    <div class="col-md-4">
        <h2>Love</h2>
        <p>
            <em>"But charity is the pure love of Christ, and it endureth forever; and whoso is found possessed of it at the last day, it shall be well with him."</em>
        </p>
        <p>- Moroni 7:47</p>
    </div>
    <div class="col-md-4">
        <h2>Serve</h2>
        <p>
            <em>“Perhaps I may be an instrument in the hands of God to bring some soul to repentance; and this is my joy.”</em>
        </p>
        <p>- Alma 29:9</p>
    </div>
</div>

IS403Project1/IS403Project1/Views/Mission/Index.cshtml

@{
    ViewBag.Title = "Index";
}
<div class=" jumbotron jumbotron2">
    <h1 id="center">Missions</h1>
    <p class="lead" id="jumbotext"></p>
<div class="container">
    <div class="col-md-5"></div>
    <div class="col-md-4">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle btn-lg" type="button" data-toggle="dropdown">
                Choose here
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Brazil", "MissionPage", "Mission", new { mission_ID = 1 }, null)</li>
                <li>@Html.ActionLink("New York", "MissionPage", "Mission", new { mission_ID = 2 }, null)</li>
                <li>@Html.ActionLink("Arizona", "MissionPage", "Mission", new { mission_ID = 3 }, null)</li>
            </ul>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
   
</div>


IS403Project1/IS403Project1/Views/Mission/MissionPage.cshtml
@model IEnumerable<IS403Project1.Models.Missions>
@{
    ViewBag.Title = "MissionPage";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Mission")">Mission</a></li>
    <li class="breadcrumb-item active">Mission Page</li>
</ol>

@foreach (var item in ViewBag.missions)
{
 <h2> @(item.missionName + " ") Mission FAQ</h2>
<div class="row">
    <div class="col-md-6">
        <img src="~/Content/imgs/@item.missionFlag" class="img img-responsive img-rounded" />
    </div>
    <div class="col-md-6">
        <h4>Mission President</h4>
        <p>&emsp;@item.missionPresidentName</p>

        <h4>Mission Address</h4>
        <p>&emsp;@item.missionAddress</p>

        <h4>Mission Language</h4>
        <p>&emsp;@item.missionLanguage</p>

        <h4>Climate</h4>
        <p>&emsp;@item.missionClimate</p>

        <h4>Main Religion</h4>
        <p>&emsp;@item.missionDominantReligion</p>

    </div>

</div>
    }
<div class="row">
    <h3>FAQ's</h3>
</div>
@foreach (var item in ViewBag.questions)
{
    <div class="panel panel-primary">
        <div class="panel-heading panel-primary"></div>
        <div class="panel-body">
            <p>@item.question</p>
            <a href="#hidden" data-toggle="collapse" class="btn btn-primary btn-sm">Reply</a>
            <form id="hidden" class="collapse">
                <textarea rows="6" cols="100">
            Input Your Response Here!
        </textarea><br />
                @Html.ActionLink("Submit", "MissionPage", "Mission", new { iMishName = @ViewBag.MishName }, new { @class = "btn btn-primary btn-sm" })
            </form>
        </div>
    </div>
}

<div class="row">
    <h4>Questions</h4>
    <p>
        Please give us some of the questions you would like to have answered! We love to hear
        what you are wanting to know more about. Thanks!
    </p>
    <form>
        <textarea rows="6" cols="100">
            Input Your Questions Here!
        </textarea><br />
        @Html.ActionLink("Submit", "MissionPage", "Mission", new { iMishName = @ViewBag.MishName }, new { @class = "btn btn-primary btn-sm" })
    </form>
</div>

IS403Project1/IS403Project1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Prepare to Serve", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Missions", "Index", "Mission")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container" id="contact">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="row" id="contact-box">

                        <h2 class="text-center">
                            <a type="button" href="mailto:joshromo12@gmail.com"><span class="fa fa-envelope"></span></a>
                            <strong>|</strong>
                            <a type="button" href="https://www.linkedin.com/in/josueromo/" target="_blank"><span class="fa fa-linkedin-square"></span></a>
                            <strong>|</strong>
                            <a type="button" href="https://www.facebook.com/josue.romo.902" target="_blank"><span class="fa fa-facebook-square"></span></a>     
                        </h2>
                    </div>
                </div>
            </div>
        </footer>
      
        <footer>
            <div class="col-lg-12 text-center">
                <p>&copy; @DateTime.Now.Year</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>